spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: rajmal
    url: jdbc:mysql://localhost:3306/bus_reservation_database
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
